# Generated by Django 5.1.4 on 2025-02-05 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'logindetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SellerDetails',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=255)),
                ('account_age_months', models.FloatField(default=0)),
                ('return_rate_per_100', models.FloatField(default=0)),
                ('fulfillment_rate', models.FloatField(default=0)),
                ('delay_rate', models.FloatField(default=0)),
                ('cancelled_rate', models.FloatField(default=0)),
                ('listings', models.IntegerField(default=0)),
                ('sentiment', models.FloatField(default=0)),
                ('category', models.CharField(choices=[('Office Products', 'Office Products'), ('Electronics', 'Electronics'), ('Home & Kitchen', 'Home & Kitchen'), ('Clothing', 'Clothing')], default='Office Products', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sellerdetails',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
