# Generated by Django 5.1.4 on 2025-02-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerdetails',
            options={'managed': False},
        ),
    ]
