# Generated by Django 5.1.4 on 2025-02-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_alter_sellerdetails_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginDetails',
        ),
    ]
