# Generated by Django 5.1.4 on 2025-01-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(db_column='Seller_Name', max_length=255)),
                ('category', models.CharField(db_column='Category', max_length=255)),
                ('item_name', models.CharField(db_column='Item', max_length=255)),
                ('image_address', models.URLField(db_column='Image_Address')),
            ],
            options={
                'db_table': 'product_details',
            },
        ),
    ]
