# Generated by Django 5.1.4 on 2025-01-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetails',
            options={'managed': False},
        ),
    ]
