# Generated by Django 5.1.4 on 2025-01-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productdetails_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productdetails',
            table='productdetails',
        ),
    ]
