# Generated by Django 5.1.4 on 2025-02-05 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerDetails',
            fields=[
                ('buyer_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ip_address', models.CharField(max_length=255)),
                ('no_payments', models.IntegerField(default=0)),
                ('no_orders', models.IntegerField(default=0)),
                ('Credit_Score', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Temp_Mail_or_VPN', models.CharField(max_length=4)),
                ('no_returns', models.IntegerField(default=0)),
                ('return_to_order', models.DecimalField(decimal_places=4, max_digits=4)),
                ('Account_Age', models.IntegerField(default=0)),
                ('Cred_change', models.DecimalField(decimal_places=3, max_digits=6)),
                ('retorder', models.DecimalField(decimal_places=3, max_digits=6)),
                ('VPN', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'buyerdetails',
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('product_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_id', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('account_age', models.DecimalField(decimal_places=2, max_digits=5)),
                ('return_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fulfillment_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('delay_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cancelled_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item', models.CharField(max_length=255)),
                ('image_address', models.URLField(max_length=2083)),
                ('description', models.TextField(max_length=4000)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'productdetails',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('reviewcontent', models.TextField(max_length=2000)),
                ('buyer', models.ForeignKey(db_column='buyer_id', on_delete=django.db.models.deletion.CASCADE, to='review.buyerdetails')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='review.productdetails')),
            ],
            options={
                'db_table': 'reviews',
                'unique_together': {('buyer', 'product')},
            },
        ),
    ]
